### ISSUE TITLE
All my pages appear blank after installing advancedmeta HTTP ERROR 500

### ISSUE THREAD

**Issue by SamiWey** [wikimedia/mediawiki-extensions-AdvancedMeta#1]
```
thrown in /home/(user)/public_html/includes/registration/ExtensionRegistry.php on line 438

[06-Mar-2020 08:09:30 America/New_York] PHP Warning:  Use of undefined constant ‘display_errors’ - assumed '‘display_errors’' (this will throw an Error in a future version of PHP) in /home/(user)/public_html/LocalSettings.php on line 200

[06-Mar-2020 08:09:30 America/New_York] PHP Fatal error:  Uncaught UnexpectedValueException: callback '\AdvancedMeta\Extension::onRegistration' is not callable in /home/(user)/public_html/includes/registration/ExtensionRegistry.php:438

Stack trace:

#0 /home/(user)/public_html/includes/registration/ExtensionRegistry.php(187): ExtensionRegistry->exportExtractedData(Array)

#1 /home/(user)/public_html/includes/Setup.php(143): ExtensionRegistry->loadFromQueue()

#2 /home/(user)/public_html/includes/WebStart.php(81): require_once('/home/(user)/...')

#3 /home/(user)/public_html/index.php(41): require('/home/(user)/...')

#4 {main}

  thrown in /home/(user)/public_html/includes/registration/ExtensionRegistry.php on line 438
```

MediaWiki 1.34.0 PHP 7.2.28 (litespeed) MariaDB 10.2.31-MariaDB-cll-lve ICU 63.1
and Advanced meta extension version for mediawiki 1.34
kernel version 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64

**Comment by aklapper** [comment]
If this is still an issue in a supported MediaWiki version, then please report this to https://phabricator.wikimedia.org/maniphest/task/edit/?projects=MediaWiki-extensions-AdvancedMeta - thanks!
